# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:13.1-alpine
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:                                #Better practice: Using a ConfigMap to store environment variable
            - name: POSTGRES_USER             #Specifying the Database user. Default: postgres
              value: theTaskMaster332
            - name: PGDATA                    #When postgres starts it needs to know the location of the data area.
              value: /data/pgdata             #The location must be specified by the PGDATA environment variable; there is no default.
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1024Mi


---


# Service to access the psql Statefulset
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-data-svc
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432


